package pt.carrismetropolitana.mobile

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Divider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.graphics.toColorInt
import androidx.navigation.NavController
import androidx.navigation.compose.rememberNavController
import pt.carrismetropolitana.mobile.composables.components.Pill

// Dummy data class for transit lines
data class TransitLine(
    val shortName: String,
    val longName: String,
    val textColor: Color,
    val pillColor: Color
)

// Dummy transit lines data
//val dummyTransitLines = listOf(
//    TransitLine("1523", "Agualva Cacém (Estação) - Oeiras (Estação)", Color.White, Color("#C61D23".toColorInt())),
//    TransitLine("1109", "Carnaxide via Outurela | Circular", Color.White, Color("#3D85C6".toColorInt())),
//    TransitLine("4906", "Setúbal (ITS) - Vendas Novas via Landeira", Color.White, Color("#BB3E96".toColorInt())),
////    TransitLine("CP", "Oeiras - São Pedro (Serviço Ocasional)", Color.White, Color("#2A9057".toColorInt()))
//)

val dTransitLines = listOf(
    TransitLine("1001", "Alfragide (Estr Seminario) - Reboleira (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1002", "Alfragide (Força Aérea) - Amadora (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1003", "Amadora (Estação Norte) - Amadora Este (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1004", "Amadora (Estação Norte) via Moinhos da Funcheira | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1005", "Amadora (Estação Norte) - UBBO", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1006", "Amadora (Estação Norte) - UBBO | Noturna", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1007", "Casal São Brás - Amadora (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1008", "Amadora Este (Metro) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1009", "Amadora (Hospital) Via Mina e Venteira | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1010", "Brandoa (Pólo Escola) - Casal da Mira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1011", "Brandoa (Largo) - Reboleira (Metro) | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1012", "Alfornelos Metro via Brandoa | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1013", "Amadora (Cemitério) - Atalaia (Escola Secundária) via Casas do Lago", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1014", "Amadora (Cemitério) - Vila Chã via Casas do Lago", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1015", "Reboleira (Estação) via Damaia | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1101", "Alfragide (Centro Comercial) - Algés (Estação) via Carnaxide Esc. Sec", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1103", "Algés (Estação) - Queijas (PSP)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1105", "Carnaxide (Escola Secundária) - Queluz Baixo (Centro Comercial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1106", "Queluz Baixo (Centro Comercial) - Algés (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1107", "Algés (Estação) - Queluz Baixo via Queijas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1109", "Carnaxide via Outurela | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1110", "Carnaxide via Queijas | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1111", "Massamá-Barcarena (Estação Sul) - Barcarena (Fábrica Pólvora)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1113", "Algés (Estação) via Cruz Quebrada e Linda-a-Velha | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1114", "Algés (Estação) via Linda-a-Velha e Miraflores | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1115", "Caxias (Ped Italiana) - Lage (Centro) via Escolas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1117", "Caxias (Qta Moura) - Paço de Arcos (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1119", "Leceia (Rotunda Idade Cobre) - Paço De Arcos (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1120", "Oeiras (Estação Norte) - Paço De Arcos (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1121", "Oeiras | Circular via Piscina Oceânica", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1122", "Bº Joaquim Matias - Caxias (Ped Italiana)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1123", "Paço De Arcos (Estação Norte) - Porto Salvo (Lagoas Park)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1124", "Paço de Arcos | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1125", "Porto Salvo | Circular via Leião e Lage", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1201", "Terrugem (Escola) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1204", "Rio de Mouro (Estação Norte) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1205", "Algueirão-Mem Martins (Estação) - Mem Martins (Esc Secundária)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1206", "Algueirão-Mem Martins (Estação) - Portela de Sintra (Estação) via Tribunal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1208", "Almargem Bispo (Cemitério) - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1209", "Bairro da Felosa - Mira Sintra (Mercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1210", "Bairro Fitares - Mem Martins (Esc Secundária)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1211", "Belas (Samaritana) - Agualva-Cacém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1212", "Venda Seca - Queluz (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1213", "Bº Joaquim Fontes (Centro Comercial) - Agualva-Cacém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1215", "Agualva-Cacém (Estação) via Encosta S. Marcos | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1216", "Tercena (Estação) via São Marcos e Casal do Cotão | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1217", "Agualva-Cacém (Estação) - Massamá (Urbanização Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1218", "Agualva-Cacém (Estação) - Mira Sintra (Mercado) via Av Bomb Vol", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1219", "Agualva-Cacém (Estação) - Mira Sintra (Mercado) via Av Santa Maria", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1220", "Agualva-Cacém (Estação) via S. Marcos (Largo) | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1221", "Agualva-Cacém (Estação) via Lopas | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1222", "Agualva-Cacém (Estação) via Bairro Joaquim Fontes | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1223", "Agualva-Cacém (Estação) - Portela Sintra (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1224", "Belas Clube Campo - Monte Abraão (Estação) via Carregueira (Estabelecimento Prisional)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1225", "Agualva-Cacém (Estação) Via Enc. S. Marcos Univ Católica e Bela Vista | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1226", "Massamá (Casal Olival) - Queluz - Belas (Estação)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1228", "Massamá-Barcarena (Estação Norte) via Belas | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1229", "Massamá-Barcarena (Estação Norte) via Quinta das Flores | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1230", "Monte Abraão (Estação) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1231", "Mem Martins (Esc. Ferreira Castro) - Coutinho Afonso", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1232", "Rio de Mouro (Estação) via Mem Martins | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1233", "Agualva-Cacém (Estação) Via Bela Vista Univ Católica e Enc. S. Marcos| Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1234", "São Pedro Sintra (Chão Meninos) - Mira Sintra (Junta Freguesia)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1235", "Covas Ferro - Mercês (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1236", "Alto do Forte (Centro Comercial) - Queluz - Belas (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1240", "Negrais (Soc Recreativa) - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1241", "Almoçageme (Mercado) - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1242", "Casais Cabrela (Largo) - Almoçageme (Mercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1244", "Casal de Cambra (Escola) - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1245", "Catribana (Largo) - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1246", "Fontanelas - Portela de Sintra (Estação Norte) via Casal da Granja", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1247", "Fontanelas - Portela de Sintra (Estação) via Janas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1248", "Portela Sintra (Estação Norte) - Praia Maçãs (Mercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1249", "Portela Sintra (Estação Norte) - Magoito (Praia)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1250", "Portela Sintra (Estação Norte) - Praia Grande", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1251", "Alto Do Forte (Centro Comercial) - Rio De Mouro (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1252", "Portela Sintra (Estação Sul) via Ranholas | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1253", "Sintra (Estação) via Cabo da Roca | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1254", "Portela Sintra (Estação Norte) - Magoito (Praia)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1255", "Rebanque - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1501", "Reboleira (Estação) via ZI Alfragide | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1502", "Algés (Estação) - Amadora (Estação Sul) via Linda-a-Velha", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1503", "Algés (Estação) - Bº Zambujal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1504", "Algés (Estação) - Bº Zambujal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1506", "Amadora (Hospital) via Alfragide e Damaia| Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1507", "Caxias (Estação) - Reboleira (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1508", "Almargem Bispo (Centro Saúde) - Amadora Este (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1509", "Amadora (Hospital) - Casal de Cambra (C. Saúde)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1510", "Amadora (Hospital) - Damaia De Baixo (Pavilhão Desportivo)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1511", "Monte Abraão (Estação) via Cemitério e Amadora (Hospital) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1512", "Amadora (Hospital) - Montelavar (Largo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1513", "Amadora (Hospital) via Escola Padre Alberto Neto | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1514", "Amadora (Hospital) via Alfornelos| Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1515", "A-da-Beja - Amadora Este (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1516", "Casal Cambra (Igreja) - Monte Abraão (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1517", "Casal de Cambra (C Rebentão) - Reboleira (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1518", "Monte Abraão - Queluz (4 Caminhos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1519", "Queluz (Palácio) - Serra Silveira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1520", "Algés (Estação) - Agualva-Cacém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1521", "Algés (Estação) - Agualva-Cacém (Estação) via A5", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1522", "Algés (Estação) - Monte Abraão (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1523", "Agualva-Cacém (Estação) - Oeiras (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1524", "Tercena (Estação) | Circular via Casal do Cotão – Taguspark", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("1525", "Caxias (Estação) - Monte Abraão (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1527", "Cruz Quebrada (Estação) - Queluz Baixo (Centro Comercial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1528", "Linda-a-Velha (Esc Secundária) - Queluz - Belas (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1529", "Oeiras (Estação Norte) - Oeiras Golf Residence", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1530", "Oeiras (Estação Norte) - Queluz (4 Caminhos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1531", "Paço De Arcos (Estação Norte) - São Marcos (Rotunda)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1601", "Porto Salvo (Centro) - Amadora Este (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1602", "Carcavelos (Praia) - Queluz (4 Caminhos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1603", "Amadora (Estação Norte) - Caneças (Largo Vieira Caldas)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1604", "Oeiras (Estação Norte) | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1605", "Carnaxide (Av. João Paulo II) - Carcavelos (Nova SBE) via A5", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1606", "Carnaxide (Av. João Paulo II) - Carcavelos (Nova SBE) via Terrugem", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1608", "Oeiras (Estação Norte) - Taguspark (Rotunda Sef)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1609", "Oeiras (Estação Norte) - Talaíde (Igreja)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1610", "Paço De Arcos (Estação Norte) - Talaíde (Campo Futebol)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1611", "Paço de Arcos (Estação Norte) - Talaíde (Campo Futebol) via Vila Fria", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1612", "Agualva Cacém (Estação) - Carcavelos (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1613", "Agualva-Cacém (Estação) - Oeiras (Estação Sul) via Trajouce", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1614", "Carcavelos (Estação) - Portela Sintra (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1615", "Carcavelos (Estação) - Rio De Mouro (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1616", "Paço de Arcos (Estação Norte) – Talaíde (Campo Futebol) via Esc. Prep. Paço de Arcos", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1617", "Talaíde (Igreja) - Paço De Arcos (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1622", "Agualva-Cacém (Estação) - Carcavelos (Estação) via Trajouce", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1623", "Cascais (Terminal) - Portela Sintra (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1624", "Cascais (Terminal) - Portela Sintra (Estação Norte) via Cabo Roca", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1625", "Cascais (Terminal) - Rio De Mouro (Estação Sul) | Expresso", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1626", "CascaiShopping (Terminal) - Portela Sintra (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1627", "CascaiShopping (Terminal) - Rio De Mouro (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1628", "Estoril (Estação) - Rio De Mouro (Estação Sul) via Amoreira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1629", "Estoril (Estação) - Portela Sintra (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1630", "Estoril (Estação) - Portela Sintra (Estação Sul) via Monte Estoril", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1631", "Estoril (Estação) - Rio De Mouro (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1632", "Casais Cabrela (Largo) - Portela Sintra (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1633", "Ericeira (Terminal Rodoviário) - Portela Sintra (Estação Norte) via Praia S. Julião", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1634", "Fonte Da Aranha - Montelavar (Largo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1635", "Almargem Bispo (Largo) - Caneças (Largo Vieira Caldas)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1636", "Caneças (B Maria Teresa) - D Maria (Igreja)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1637", "Casal Cambra - Vale Lobos (Largo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1638", "Oeiras (Estação Norte) - Parede (Terminal) via Escola", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1703", "Amadora (Estação Norte) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1704", "Amadora (Hospital) - Marquês Pombal (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1706", "Benfica (R Pereira Bernardes) - Brandoa (Alto)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1707", "Casal Mira (Escola Primária) - Colégio Militar (Metro) via Amadora Este (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1708", "Casal Mira (Centro Comercial) – Brandoa (Alto) via Colégio Militar", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1709", "Caneças (Largo Jardim) - Colégio Militar (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1710", "Caneças (Largo Jardim) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1711", "Caneças (Esc. Secundária) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1712", "Algés (Estação) - Amadora (Estação Sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1713", "Algés (Estação) - Damaia (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1714", "Amadora (Estação Sul) - Belém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1715", "Belém (Estação) - Mira Sintra (Mercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1716", "Idanha (Urb Campinas) - Marquês Pombal (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1717", "Tercena - Colégio Militar (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1718", "Grajal - Belém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1719", "Casal de Cambra - Colégio Militar (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1720", "Casal de Cambra - Colégio Militar (Metro) via Queluz-Belas (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1721", "Massamá (Casal Olival) - Queluz (4 Caminhos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1722", "Alfragide (Centro Comercial) - Hospital São Francisco Xavier", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1723", "Carnaxide (Av Portugal) - Marquês Pombal (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1724", "Linda-a-Velha (Alto Sta Catarina) – Marquês Pombal (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1725", "Marquês Pombal (Metro) - Oeiras (Estação Norte)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1726", "Marquês Pombal (Metro) - Queijas (PSP)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1728", "Marquês Pombal (Metro) - Queijas (PSP) via Alto Sta Catarina", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1729", "Marquês Pombal (Metro) - Queijas (PSP)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1730", "Marquês Pombal (Metro) - Queluz Baixo (Centro Comercial) via Linda-a-Velha", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1731", "Agualva-Cacém (Estação) - Hospital São Francisco Xavier", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("1733", "Marquês Pombal (Metro) - São Marcos via Queijas (Rotunda) e Taguspark", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2002", "A-dos-Cãos - Loures (Centro Saúde)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2003", "Guerreiros - Guerreiros", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2004", "Bairro de Santa Maria - Loures (Centro Saúde)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2006", "Bucelas - Vila de Rei | Circular via Vila Nova", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2008", "Bucelas - Mato da Cruz | Circular via Solcasa", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2011", "Cabeço de Montachique - Loures (C Saúde) via Bairro Novo de Palhais e Murteira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2013", "Conventinho - Torres da Bela Vista", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2014", "Escola Maria Veleda - Frielas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2015", "Flamenga - Torres da Bela Vista", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2016", "Guerreiros - Hospital Beatriz Ângelo", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2017", "Guerreiros - Loures Loures (Centro Saúde)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2020", "Sto. Ant. Cavaleiros | Circular via Hospital Beatriz Ângelo", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2021", "Santo Antão do Tojal | Circular via Loures", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2026", "Loures | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2027", "Loures | Circular via Cidade Nova", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2028", "Loures | Circular via Ponte Frielas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2029", "Moscavide (Urbanização Jardins do Cristo Rei) | Circular via Portela", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2030", "Sacavém (C.Saúde) - Sacavém (Centro Saúde) via Fetais", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2031", "Sacavém (C.Saúde) - Sacavém (Centro Saúde)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2032", "Sacavém (Estação) | Circular via São João da Talha", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2034", "S.Iria (Apeadeiro) - Sta Iria Azoia (Est) circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2035", "Tojal Jardim - Sto Antao Tojal via MARL", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2036", "Bairro Angola - Bairro Angola via Camarate", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2037", "Zambujal | Circular via Infantado", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2038", "Bucelas - Loures | Circular via Ribas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2039", "Bucelas - Zambujal via Sete Casas e Loures", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2103", "Antas - Mafra (Parque Desportivo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2104", "Avessada - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2105", "Barreiralva - Mafra (Parque Desportivo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2106", "Bocal - Mafra (Parque Desportivo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2107", "Bocal - Malveira (Terminal) via Avessada e Portela", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2108", "Cachoeira - Malveira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2109", "Cachoeira - Venda do Pinheiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2110", "Carvalhal - Mafra (Parque Desportivo) via Mata Grande e Valverde", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2112", "Casais de São Lourenço - Ericeira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2113", "Ericeira (Terminal) - Casais de São Lourenço via Feiteira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2114", "Charneca - Lagoa (Colégio Miramar)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2116", "Encarnação - Mafra (Parque Desportivo)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2117", "Encarnação (Cemitério) - Ericeira (Terminal) via Ribamar", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2118", "Encarnação (Cemitério) - Ericeira (Terminal) via Santo Isidoro e Monte Godel", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2120", "Enxara do Bispo - Ericeira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2121", "Enxara do Bispo - Gradil", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2122", "Livramento - Enxara do Bispo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2123", "Praia da Foz do Lizandro - Praia de Ribeira d'Ilhas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2124", "Urbana da Ericeira 1 | Circular via Colinas Atlantico", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2125", "Urbana da Ericeira 2 | Circular via Outeirinho e Fonte Boa da Brincosa", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2126", "Ericeira | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2127", "Ericeira (Terminal) - Barril", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2128", "Ericeira (Terminal) - Fonte Boa da Brincosa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2132", "Ericeira (Terminal) - Mafra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2133", "Ericeira (Terminal) - Mafra (Palácio) via Carvoeira Montesouros e Av. Portugal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2134", "Ervideira - Gradil", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2135", "Igreja Nova - Venda do Pinheiro (Núcleo Empresarial sul)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2136", "Jerumelo - Mafra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2141", "Mafra (Terminal) - Ribamar", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2142", "Mafra (Almada) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2143", "Mafra (Palácio) - Zambujal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2144", "Mafra (Parque Desportivo) - Livramento", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2145", "Mafra | Circular via Sobral da Abelheira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2146", "Malveira (Centro Saúde) - Milharado (CASO) | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2147", "Milharado - Venda do Pinheiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2148", "Póvoa da Galega - Venda do Pinheiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2149", "Prezinheira - Venda do Pinheiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2150", "Carvalhal - Venda do Pinheiro (Colégio Santo André)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2151", "Venda do Pinheiro (Terminal) - Vila de Canas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2201", "Arroja - Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2202", "Arroja - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2203", "Arroja | Circular via Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2204", "Caneças - Famões", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2205", "Caneças (Esc. Secundária) - Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2206", "Caneças (Esc. Secundária) - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2207", "Caneças (Esc. Secundária) - Sr. Roubado (Metro) via Odivelas (Centro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2208", "Caneças (Jardim) - Vale Nogueira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2209", "Casal Bispo - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2210", "Jardim da Amoreira - Colinas do Cruzeiro | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2211", "Jardim da Amoreira - Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2212", "Odivelas (C. Comercial) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2213", "Odivelas (Metro) - Famões | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2215", "Odivelas (Metro) - Ramada (Bons Dias)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2216", "Odivelas (Metro) - Ramada (Jardim da Radial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2217", "Odivelas (Metro) | Circular via Casal Chapim", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2218", "Odivelas (Metro) | Circular via Colinas do Cruzeiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2219", "Odivelas (Metro) | Circular via Póvoa de Santo Adrião", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2220", "Olival Basto | Circular via Póvoa de Santo Adrião e Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2221", "Póvoa de Santo Adrião (Parque Urbano) - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2222", "Ramada | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2223", "Sr. Roubado (Metro) | Circular via Casal Novo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2224", "Arroja | Circular via Patameiras (C. Comercial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2225", "Odivelas (Metro) | Circular via Arroja", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2303", "Alverca (Est) - Arcena", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2304", "Alverca (Estação) - Alhandra", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2306", "Alverca (Est) - Vila Franca Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2307", "Arcena - Vila Franca Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2309", "Bogalhão - Vila Franca Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2310", "Torre de Cima e Capela - Carregado (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2315", "Castanheira do Ribatejo (Estação) | Circular via Hospital", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2316", "Cotovios - Vila Franca Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2317", "Fonte Santa - Póvoa Santa Iria (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2318", "Póvoa de Santa Iria (Estação) | Circular via Forte da Casa", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2319", "F. Casa(Lgo) - Forte Casa (Largo) circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2325", "P.S.I.(Est) - Verdelha Ruivo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2327", "P.S.I.(Est) - P. S. Iria (Est) via Vialonga", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2328", "QªPied - Vila Franca Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2329", "Alhandra(Esc) - Sobralinho", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2331", "Torre Cima i Capela - Hospital VFX", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2333", "V.Franca Xira - Hospital VFX via N1", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2335", "P.S.Iria (Praça República) - Póvoa Sta Iria via Bragadas", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2336", "P.S.Iria(Rep)_P.S.Iria(Rep)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2337", "Vila Franca de Xira (Estação) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2501", "Bocal - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2502", "Bucelas - Malveira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2504", "Carrascal - Ponte de Lousa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2505", "Loures (C. Comercial) - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2506", "Milharado (CASO) - Ponte de Lousa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2511", "Bairro dos CTT - Loures (C. Comercial C. Loures)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2513", "Caneças (Esc. Secundária) - Loures (Supermercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2515", "Casal Paradela - Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2516", "Casal Paradela - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2517", "Odivelas (Metro) - Hospital Beatriz Ângelo | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2518", "Frielas (Zona Comercial) - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2519", "Loures (C. Comercial C. Loures) - Odivelas (Colinas do Cruzeiro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2521", "Loures (C.C. Continente) - Odivelas (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2522", "Montemor - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2523", "Odivelas (Metro) - Montemor", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2524", "Odivelas (Metro) | Circular via Hospital Beatriz Ângelo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2525", "Santo Antão do Tojal - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2530", "Alverca (Estação) - Bucelas via Malvarosa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2532", "Alverca(Est) - Loures", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2533", "Alverca (Estação) - Santo Antão do Tojal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2534", "Loures (Supermercado) - Santa Iria Azoia", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2535", "Loures - Vila Franca de Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2536", "Mojões - Bairro Monjoes via Póvoa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2537", "P.S.I.(Est) - Santo Antão Tojal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2538", "P.S.I.(Est) - Santo Antao Tojal via Alpriate", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2539", "Santa Iria da Azóia (Estação) | Circular via São João da Talha", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2540", "S. Iria (Apeadeiro) - MARL", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2601", "Loures (C. Comercial C. Loures) - Reboleira (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2605", "Cacém (Estação) - Loures (Supermercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2610", "Odivelas (Metro) - UBBO", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2611", "Ramada (Bons Dias) - UBBO", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2620", "Covas de Ferro - Loures (Centro Saúde)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2621", "Covas de Ferro - Pinheiro de Loures", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2625", "Mafra (Terminal)- São João das Lampas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2626", "Mafra (Parque Desportivo) - Portela de Sintra (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2627", "Mafra (Parque Desportivo) - Ribeira dos Tostões", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2630", "Caneças (Esc. Secundária) | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("2632", "Casal de Cambra (C. Saúde) - Odivelas (Metro) via Bairro Sol Nascente", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2650", "Cidade Nova - Costa da Caparica", Color("#FFFFFF".toColorInt()), Color("#0C807E".toColorInt())),
    TransitLine("2651", "Bucelas - Costa da Caparica (Terminal)", Color("#FFFFFF".toColorInt()), Color("#0C807E".toColorInt())),
    TransitLine("2652", "Costa da Caparica - Forte Casa (Largo)", Color("#FFFFFF".toColorInt()), Color("#0C807E".toColorInt())),
    TransitLine("2701", "Pontinha (Metro) - Vale Grande", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2702", "Lisboa (C. Grande) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2703", "Lisboa (C. Grande) | Circular via Bairro São José", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2706", "Bucelas - Lisboa (C. Grande) via Infantado", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2708", "C.Aguieira - Estação Oriente", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2709", "Bairro de Angola | Circular via Camarate", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2710", "A. Moinho - Campo Grande", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2711", "Charneca - Lisboa (Oriente) via Bairro de Santiago", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2713", "Lisboa (C. Grande) | Circular via Charneca", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2714", "Lisboa (C. Grande) - Sacavém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2715", "Lisboa (C. Grande) - Cidade Nova via IC22", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2716", "Cidade Nova - Lisboa (C. Grande) via IC22", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2717", "Lisboa (C. Grande) - Torres da Bela Vista via IC22", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2718", "Infantado - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2719", "Lisboa (C. Grande) - Loures", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2720", "Lisboa (C. Grande) - Loures (Bairro Urmei)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2722", "Areeiro - Via Rara", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2723", "Lisboa (C. Grande) - Zambujal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2724", "Estação Oriente - Loures via Tunel Grilo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2725", "Estação Oriente - Loures (zona comercial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2726", "Estação Oriente - Loures via Camarate", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2727", "Lisboa (Oriente) - Loures (HBA exterior)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2728", "Bairro Covina - Estação Oriente", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2729", "Estação Oriente - Portela Azóia", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2730", "Estação Oriente - Santa Iria Azóia", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2731", "Estação Oriente - Estação Oriente via Portela", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2733", "Loures (Supermercado) - Moscavide (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2734", "Prior Velho - Sacavém (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2735", "Urbana de Sacavém | Circular via Prior Velho", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2736", "Campo Grande - Campo Grande via Sacavém", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2740", "Ericeira (Terminal) - Lisboa (C. Grande) via A8", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2741", "Ericeira (Terminal) - Lisboa (C. Grande) via Freixeira e A8", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2742", "Lisboa (C. Grande) - Mafra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2743", "Lisboa (C. Grande) - Póvoa da Galega via A8 e Sete Casas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2744", "Lisboa (C. Grande) - Póvoa da Galega via A8 Lousa e Freixeira", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2745", "Póvoa da Galega - Lisboa (C. Grande) via Murteira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2746", "Lisboa (C. Grande) - Venda do Pinheiro via Milharado e A8 Lousa", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2750", "Bucelas - Lisboa (C. Grande) via C. Montachique Odivelas (Metro) e Lumiar", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2751", "Ericeira (Terminal) - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2752", "Lisboa (C. Grande) - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2753", "Lisboa (C. Grande) - Milharado (CASO) via Lousa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2754", "Lisboa (C. Grande) - Póvoa da Galega via Guerreiros e Lousa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2755", "Lisboa (C. Grande) - Póvoa da Galega via Casais do Forno", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2756", "Lisboa (C. Grande) - Póvoa da Galega via Urbanização do Almirante", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2758", "Lisboa (C. Grande) - Mafra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2761", "Bucelas - Lisboa (C. Grande) via Cabeço de Montachique e Ramada", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2762", "Bucelas - Lisboa (C. Grande) via Ribas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2764", "Bucelas - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2765", "Cabeço de Montachique - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2768", "Casal Paradela - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2769", "Cidade Nova - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2772", "Lisboa (C. Grande) - Torres da Bela Vista via C.Comercial", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2774", "Frielas - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2776", "Guerreiros - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2780", "Loures (C.C. Continente) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2781", "Loures (C.C. Continente) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2782", "Bucelas - Lisboa (C. Grande) via Ribas e Manjoeira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2785", "Covas de Ferro - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2790", "Alverca(Est) - Areeiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2791", "Alverca (Z.Ind) - Areeiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2792", "Arcena - Estação Oriente", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2794", "F. Casa(Lgo) - Estação Oriente", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2795", "Campo Grande - Quinta Piedade", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2796", "Lisboa (C. Grande) - Vialonga via Infantado", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2797", "Lisboa (C. Grande) - Vialonga via A8", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2801", "Ericeira (Terminal) - Lisboa (C. Grande) via A21 A8", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2802", "Lisboa (C. Grande) - Mafra (Terminal) via A21", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2803", "Ericeira (Terminal) - Lisboa (C. Grande) via Mafra e A21 A8", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2804", "Mafra - Lisboa (C. Grande) via A8", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2805", "Encarnação - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2806", "Lisboa (C. Grande) - Livramento", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2807", "Lisboa (C. Grande) - Zambujal via Mafra", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2810", "Arroja - Lisboa (C. Grande)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2811", "Caneças (Bairro do Monte Verde) - Lisboa (C. Militar)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2812", "Caneças (Esc. Secundária) - Lisboa (C. Grande) v Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2813", "Casal Novo - Lisboa (C. Militar)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2814", "Casal Novo - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2816", "Lisboa (C. Grande) - Ramada (Bairro Bons Dias)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2817", "Lisboa (C. Militar) - Odivelas (Metro) via Serra da Luz", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2818", "Lisboa (C. Militar) - Serra da Amoreira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2819", "Lisboa (C. Militar) - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2820", "Odivelas (Colinas do Cruzeiro) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2821", "Odivelas (Metro) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2822", "Odivelas (Metro) - Pontinha (Metro) via Serra da Luz", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2823", "Pedernais (Bairro Girassol) - Pontinha (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2824", "Pontinha (Metro) - Sr. Roubado (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2830", "Casal do Bispo - Lisboa (C. Militar)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2831", "Casal do Bispo - Pontinha (Metro) Via C.Saude Famoes", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2832", "Casal Novo - Lisboa (C. Militar) via Casal de Cambra", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2833", "Pontinha (Metro) - Casal Novo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2841", "Lisboa (C. Grande) - Sobralinho via A1 e Arcena", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2842", "Lisboa (C. Grande) - Vila Franca de Xira via Alverca e N10", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2850", "Costa da Caparica - Póvoa de Santo Adrião (Parque Urbano)", Color("#FFFFFF".toColorInt()), Color("#0C807E".toColorInt())),
    TransitLine("2900", "Lisboa (C. Grande) - São Sebastião", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("2901", "Rolia - Venda do Pinheiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2905", "Aranha (Rotunda) - Ericeira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#BB3E96".toColorInt())),
    TransitLine("2906", "Assenta - Encarnação Cruz", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2907", "Assenta - Ericeira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2908", "Cambelas - Encarnação Cruz", Color("#FFFFFF".toColorInt()), Color("#BB3E96".toColorInt())),
    TransitLine("2910", "Ervideira - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2911", "Ervideira - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2912", "São Sebastião - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2913", "Mafra (Parque Desportivo) - Pero Negro (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2914", "Mafra (Parque Desportivo) - São Pedro da Cadeira (Rotunda da Aranha)", Color("#FFFFFF".toColorInt()), Color("#BB3E96".toColorInt())),
    TransitLine("2915", "Vila Franca do Rosário - Malveira (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2920", "A-do-Mourão - Alverca (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2921", "V.F.Xira - Arruda Vinhos", Color("#FFFFFF".toColorInt()), Color("#BB3E96".toColorInt())),
    TransitLine("2926", "Castanheira(Est) - Vila F. Xira via Cachoeiras", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2927", "Castanheira(CP) - Vila Franca Xira via Loja Nova", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("2928", "Casais da Granja - Vila Franca Xira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3001", "Almada (Cristo Rei) - Cacilhas (Terminal)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3003", "Almada Forum - Cacilhas (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3004", "Almada Forum - Marisol", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3005", "Flexibus Almada | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3006", "Aroeira | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3007", "Bairro Fundo Fomento - Cacilhas (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3008", "Monte da Caparica - Quintinhas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3009", "Cacilhas (Terminal) - Trafaria (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3011", "Cacilhas (Terminal) - Costa da Caparica, via Escola José Cardoso Pires", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3012", "Cacilhas (Terminal) - Fonte da Telha", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3013", "Cacilhas (Terminal) - Feijó (Almada Forum)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3014", "Cacilhas (Terminal) - Raposeira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3015", "Charneca da Caparica - Cova do Vapor", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3017", "Charneca da Caparica - Pragal (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3018", "Charneca da Caparica - Sobreda", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3019", "Charneca da Caparica - Trafaria (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3020", "Charneca da Caparica | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3021", "Costa da Caparica (Terminal) - Monte da Caparica (FCT)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3022", "Costa da Caparica (Terminal) - Cacilhas (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3023", "Costa da Caparica (Terminal) - Laranjeiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3024", "Costa da Caparica (Terminal) - Pragal (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3025", "Costa da Caparica (Terminal) - Pragal (Estação), via IC20", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3026", "Cova da Piedade - Hospital Garcia de Orta, via Base Naval", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3027", "Hospital Garcia de Orta - Sobreda", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3028", "Lazarim | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3029", "Marco Cabaço | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3030", "Fonte da Telha - Monte da Caparica (FCT)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3033", "Monte da Caparica | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3034", "Porto Brandão (Terminal) - Quinta do Texugo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3037", "Quintinha | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3038", "Banática - Porto Brandão", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3040", "Cacilhas - Quinta do Texugo (Via Qta da Graça)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3041", "Cacilhas (Terminal) - Caparica (Pilotos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3101", "Amora - Foros de Amora (Estação)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3103", "Corroios (Estação) - Paio Pires (Centro), via Farinheiras", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3104", "Corroios (Estação) - Vale de Milhaços", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3105", "Fernão Ferro - Fogueteiro (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3106", "Coina (Estação) - Fernão Ferro", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3107", "Marco do Grilo - Laranjeiras", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3108", "Fogueteiro (Quinta da Mata) - Foros de Amora (Estação)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3109", "Fogueteiro (Estação) - Parque Empresarial do Seixal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3110", "Fogueteiro (Estação) - Redondos", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3111", "Fogueteiro (Estação) - Seixal (Terminal Fluvial), via Escola António Augusto Louro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3112", "Fogueteiro (Estação) - Seixal (Terminal Fluvial), via Paio Pires", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3113", "Fogueteiro (Estação) - Seixal (Terminal Fluvial), via Quinta do Cabral", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3114", "Foros de Amora (Estação) - Paio Pires (Quinta Flamância)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3116", "Marisol (Valadares) - Seixal (Terminal Fluvial), via Corroios (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3118", "Marisol (Valadares) - Seixal (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3119", "Pinhal Conde Cunha - Seixal (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3120", "Redondos - Seixal (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3121", "Seixal | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3201", "Aldeia do Meco - Sesimbra (Terminal), via Aiana", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3202", "Alfarim - Sesimbra (Terminal), via Aiana", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3203", "Azoia - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3204", "Azoia - Sesimbra (Terminal), via Serra da Azoia", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3205", "Cabo Espichel - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3206", "Carrasqueira - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3207", "Carrasqueira - Sesimbra (Terminal), via Valbom e Sampaio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3208", "Aldeia do Meco - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3209", "Fetais - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3210", "Lagoa de Albufeira - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3211", "Lagoa de Albufeira - Sesimbra (Terminal), via Sampaio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3212", "Maçã (Rua Macieira) - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3213", "Pinhal de Cima - Sesimbra (Terminal) | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3214", "Sampaio - Santana", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3215", "Fornos - Sampaio (via Aiana)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3216", "Maçã – Sampaio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3217", "Azoia - Sampaio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3218", "Sesimbra (Parque de Campismo) - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3220", "Sesimbra | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3221", "Valbom - Sesimbra (Terminal), via Sampaio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3222", "Quinta do Conde | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3223", "Sampaio (Moagem) – Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("3502", "Almada Forum - Paio Pires (Centro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3503", "Almada Forum - Vale de Milhaços", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3504", "Hospital Garcia de Orta - Quintinhas", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3505", "Cacilhas (Terminal) - Farinheiras", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3506", "Cacilhas (Terminal) - Corroios (Estação), via Miratejo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3507", "Cacilhas (Terminal) - Marisol", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3508", "Cacilhas (Terminal) - Paio Pires (Centro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3509", "Cacilhas (Terminal) - Paio Pires (Centro), via Seixal (Terminal Fluvial) e Amora", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3510", "Cacilhas (Terminal) - Pilotos", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3511", "Cacilhas (Terminal) - Pinheirinho", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3512", "Cacilhas (Terminal) - Quinta Princesa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3513", "Cacilhas (Terminal) - Santa Marta do Pinhal (Cemitério)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3514", "Cacilhas (Terminal) - Vale de Milhaços", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3515", "Corroios (Estação) - Caparica (Pilotos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3516", "Charneca da Caparica - Corroios (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3517", "Chegadinho - Corroios (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3518", "Corroios (Estação) - Vale de Figueira", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3519", "Costa da Caparica (Terminal) - Corroios (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3520", "Costa da Caparica (Terminal) - Quinta do Brasileiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3521", "Cruz de Pau - Fonte da Telha", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3522", "Fonte da Telha - Paio Pires (Centro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3523", "Fonte da Telha - Paio Pires (Quinta Flamância), via Seixal (Terminal Fluvial) e Foros de Amora (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3524", "Hospital Garcia de Orta - Marisol", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3525", "Hospital Garcia de Orta - Miratejo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3526", "Laranjeiro - Pinheirinho", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3527", "Monte da Caparica (FCT) - Paio Pires (Bairro Cucena)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3528", "Monte da Caparica (FCT) - Paio Pires (Centro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3535", "Cacilhas (Terminal) - Quinta do Conde", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3536", "Cacilhas (Terminal) - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3540", "Zambujal - Coina (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3541", "Coina (Estação) - Fernão Ferro, via Casal do Sapo e Pinhal do General", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3542", "Coina (Estação) - Praia do Meco", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3543", "Coina (Estação) - Quinta do Conde, via Estrada de Coina", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3544", "Sesimbra (Terminal) - Coina (Estação) via Marco do Grilo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3545", "Corroios (Estação) - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3546", "Cruz de Pau - Quinta do Conde", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3547", "Fogueteiro (Estação) - Quinta do Conde", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3548", "Marco do Grilo - Quinta do Conde", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3549", "Quinta do Conde - Sesimbra (Terminal), via Sampaio e Marco do Grilo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3590", "Estação de Coina – Festival SBSR", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3601", "Barreiro - Cova da Piedade (Metro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3605", "Cacilhas (Terminal) - Setúbal (ITS), via Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3615", "Barreiro - Seixal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3620", "Coina (Estação) - Quinta do Conde", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3625", "Barreiro - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3626", "Coina (Estação) - Vila Nogueira de Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3635", "Coina (Estação) - Sesimbra (Terminal), via Azeitão e Sampaio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3640", "Azoia - Vila Nogueira de Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3641", "Quinta do Conde - Sampaio, via Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3642", "Sesimbra (Terminal) - Setúbal (Hospital)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3650", "Moita - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#0C807E".toColorInt())),
    TransitLine("3701", "Almada (Hosp. Particular) - Algés (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3702", "Almada (Parque Urbano) - Lisboa (C. Universitária)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3703", "Almada (Parque Urbano) - Lisboa (Areeiro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3704", "Charneca da Caparica - Lisboa (M. Pombal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3705", "Charneca da Caparica (Centro) - Lisboa (Sete Rios)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3706", "Charneca da Caparica - Lisboa (Sete Rios), via Feijó", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3708", "Costa da Caparica (Terminal) - Lisboa (C. Sodré)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3709", "Costa da Caparica (Terminal) - Lisboa (M. Pombal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3710", "Costa da Caparica (Terminal) - Lisboa (Areeiro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3711", "Monte da Caparica (FCT) - Lisboa (Sete Rios)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3715", "Lisboa (M. Pombal) - Santa Marta do Pinhal", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3716", "Lisboa (Sete Rios) - Marisol", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3717", "Lisboa (Sete Rios) - Quinta do Brasileiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("3720", "Lisboa (Sete Rios) - Quinta do Conde", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("3721", "Lisboa (Sete Rios) - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4001", "Alcochete | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4002", "São Francisco | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4102", "Moita (Estação) - Sarilhos Pequenos via Gaio-Rosário", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4103", "Moita (Estação) - Sarilhos Pequenos", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4104", "Moita | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4106", "Alhos Vedros | Circular via Centro de Saúde", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4107", "Alhos Vedros | Circular via Arroteias", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4203", "Afonsoeiro - Montijo (Terminal Fluvial) via Bairro da Liberdade", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4204", "Bairro do Charqueirão - Montijo (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4205", "Bairro do Charqueirão - Montijo (Terminal Fluvial) via Vale Porim", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4207", "Montijo (Área Comercial) - Montijo (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4208", "Montijo (Terminal Fluvial) - Sarilhos Grandes (Estr. 4 Marcos)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4211", "Craveiras - Pegões | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4302", "Palmela (Estação) - Palmela (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4303", "Palmela | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4304", "Palmela (Terminal) - Penalva", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4305", "Brejos do Assa - Palmela (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4308", "Palmela (Terminal) - Pinhal Novo (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4312", "Poceirão - Vale Abrunheira (X) via Fernando Pó", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4313", "São Gonçalo - Penalva", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4320", "Pinhal Novo | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4321", "Pinhal Novo - Quinta do Anjo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4322", "Pinhal Novo - Rio Frio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4401", "Cachofarra - Setúbal (Hospital)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4402", "Estefanilha - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4403", "Ferro Engomar (Terminal) - Setúbal (Av. Luísa Todi) via Amoreiras", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4404", "Interfaces Setúbal | Circular", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4406", "Manteigadas - Setúbal (Mercado)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4407", "Manteigadas - Setúbal (Mercado) via Bairro 25 de Abril", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4408", "Manteigadas - Setúbal (Mercado) via Bela Vista", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4409", "Setúbal (Bº Quinta Santo António) - Setúbal (Bº Viso) via Montebelo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4410", "Manteigadas (Esc. Profissional) - Poço Mouro via Centro Comercial", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4412", "Morgada - Setúbal (Mercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4414", "Outão (Hospital) - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4415", "Outão (Hospital) - Setúbal (ITS) via vale da Rasca", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4416", "Poço Mouro - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4418", "Setúbal (Centro Comercial) - Setúbal (Av. 5 Outubro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4419", "Brejos Canes - Setúbal (Saboaria)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4420", "Setúbal (Centro Comercial) - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4421", "Setúbal (Bairro Camolas) - Setúbal (Casal Figueiras)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4422", "Setúbal (Bairro Camolas) - Setúbal (Casal Figueiras) via Bairro do Viso", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4424", "Setúbal (Bairro Viso) - Manteigadas (Piscinas)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4425", "Setúbal (Bairro Viso) - Mitrena", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4426", "Setúbal (Bairro do Viso) - Setúbal (Bairro Quinta Santo António)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4427", "Setúbal (Bela Vista) - Setúbal (Mercado)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4428", "Setúbal (Casal Figueiras) - Vale Ana Gomes", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4429", "Setúbal (Centro Saúde) - Setúbal (Mercado)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4430", "Setúbal (Hospital) - Setúbal (Montalvão)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4431", "Setúbal (ITS) - Setúbal (Quinta Varzinha)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4432", "Setúbal (ITS) - Vale de Choupo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4433", "Alto Guerra - Setúbal (Casal Figueiras)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4434", "Setúbal (Mercado 2 de Abril) - Setúbal (R. Timor)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4435", "Biscainho - Faralhão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4436", "Setúbal (Mercado) - Setúbal (Terroa)", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4437", "Faralhão - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4438", "Setúbal (Monte Belo Norte) - Setúbal (Saboaria)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4439", "Praias do Sado - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4440", "Setúbal (Monte Belo Norte) - Setúbal (Saboaria) via Centro Comercial", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4441", "Setúbal (Saboaria) - Setúbal (Vale Cobro)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4443", "Setúbal (Politécnico) - Praias do Sado", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4451", "Mitrena (Lisnave) - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4452", "Mitrena (Portucel) - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4453", "Mitrena (Portucel) - Setúbal (ITS) via Estrada Graça", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4463", "Azeitão | Circular via R. José Augusto Coelho", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4464", "Azeitão | Circular via R. Dr. Francisco Gonçalves de Oliveira", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4470", "Setúbal (ITS) - Praia do Creiro via Vila Nogueira de Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4471", "Praia Albarquel | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4474", "Praia da Figueirinha - Setúbal (Centro Comercial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4476", "Praias Arrábida | Circular", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4477", "Vaivém Arrábida", Color("#FFFFFF".toColorInt()), Color("#3D85C6".toColorInt())),
    TransitLine("4481", "Livramento-Montebelo | Circular via Bonfim", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4482", "Livramento-Montebelo | Circular via Terroa", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4501", "Alcochete (Freeport) - Montijo (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4504", "Alcochete (Freeport) - Montijo (Terminal Fluvial) via Atalaia e Passil", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4512", "Alcochete (Freeport) - Setúbal (ITS) via Alto Estanqueiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4513", "Alcochete (Freeport) - Pinhal Novo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4514", "Canha - Montijo (Terminal Rodoviário) via Pegões", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4515", "Montijo (Terminal Rodoviário) - Pegões", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4516", "Montijo (Terminal Rodoviário) - Rio Frio", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4517", "Montijo (Terminal Rodoviário) - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4521", "Faias - Pinhal Novo via Lagameças", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4523", "Montijo (Terminal Rodoviário) - Pinhal Novo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4524", "Palmela (Terminal) - Pegões", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4530", "Bairro Vila Morena - Pinhal Novo", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4531", "Moita (Esc. Secundária) - Palmela (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4532", "Moita (Estação) - Moita (Bairro 1º Maio)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4540", "Águas de Moura - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4541", "Algeruz - Setúbal (Av. Luísa Todi)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4542", "Algeruz - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4543", "Algeruz - Setúbal (ITS) via Poçoilos", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4544", "Bairro Margaça - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4545", "Biscainho - Setúbal (Bela Vista)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4546", "Biscainho - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4548", "Lagameças - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4549", "Palmela (Terminal) - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4550", "Palmela (Terminal) - Vila Nogueira de Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4551", "Palmela (Alameda Nun'Álvares Pereira) - Setúbal (Av. Luísa Todi)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4560", "São Gonçalo - Vila Nogueira de Azeitão (Escola Básica 2 3)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4562", "Setúbal (ITS) - Vila Nogueira de Azeitão (Escola) via Palmela (Estação)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4600", "Alcochete (Freeport) - Barreiro (Terminal) via Samouco", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4602", "Alhos Vedros (Estação) - Barreiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4604", "Barreiro (Terminal) - Moita (Escola Secundária)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4605", "Lavradio - Pinhal do Forno", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4610", "Bairro dos Marinheiros - Barreiro (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4611", "Penalva (Estação) - Moita (Esc. Secundária)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4612", "Bairro dos Marinheiros - Palmela (Terminal)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4620", "Moita (Esc. Secundária) - Paio Pires", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4621", "Moita (Esc. Secundária) - Seixal (Terminal Fluvial)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4632", "Coina (Estação) - Quinta do Anjo via Vendas de Azeitão", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4641", "Quinta do Conde - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4643", "Montijo (Av. Inf. D. Henrique) - Sesimbra (Terminal)", Color("#FFFFFF".toColorInt()), Color("#0C807E".toColorInt())),
    TransitLine("4701", "Lisboa (Oriente) - Vale da Amoreira", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4702", "Alcochete (Urb. Campo Belo) - Lisboa (Oriente)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4704", "Atalaia - Lisboa (Oriente) via B. Areias e B. Esteval", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4705", "Lisboa (Oriente) - Samouco", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4706", "Lisboa (Oriente) - São Francisco (Vila Azul)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4707", "Lisboa (Oriente) - Montijo (Terminal Rodoviário)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4710", "Lisboa (Oriente) - Palmela (Terminal)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4711", "Lisboa (Oriente) - Pinhal Novo", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4715", "Lisboa (Oriente) - Setúbal (Terminal Várzea) via Pinhal Novo", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4720", "Lisboa (Oriente) - Setúbal (Terminal Várzea)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4725", "Lisboa (Sete Rios) - Setúbal (Terminal Várzea)", Color("#FFFFFF".toColorInt()), Color("#FDB71A".toColorInt())),
    TransitLine("4730", "Lisboa (Sete Rios) - Setúbal (ITS) via Fogueteiro", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4901", "Landeira - Setúbal (ITS)", Color("#FFFFFF".toColorInt()), Color("#C61D23".toColorInt())),
    TransitLine("4905", "Faias - Vendas Novas", Color("#FFFFFF".toColorInt()), Color("#BB3E96".toColorInt())),
    TransitLine("4906", "Setúbal (ITS) - Vendas Novas via Landeira", Color("#FFFFFF".toColorInt()), Color("#BB3E96".toColorInt())),
    TransitLine("CP", "Oeiras - São Pedro do Estoril", Color("#FFFFFF".toColorInt()), Color("#2A9057".toColorInt())),

    )

@Composable
fun LinesList(transitLines: List<TransitLine>, navController: NavController) {
    LazyColumn() {
        itemsIndexed(
            items = transitLines,
        ) {index, line ->
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier
                    .padding(16.dp)
                    .clickable { navController.navigate("line_details/${line.shortName}") }
            ) {
                Pill(text = line.shortName, color = line.pillColor, textColor = line.textColor, size = 60)
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = line.longName,
                    fontSize = 16.sp, // Set font size in scaled pixels (sp)
                    fontWeight = FontWeight.Bold,
                    modifier = Modifier.weight(1f)
                )
            }
            if (index < transitLines.size - 1) {
                Divider(color = Color.LightGray, thickness = 1.dp)
            }
            Spacer(modifier = Modifier.height(8.dp))
        }
    }
}

@Preview
@Composable
fun DummyLinesListPreview() {
    LinesList(transitLines = dTransitLines, navController = rememberNavController())
}